@ProposalAPI.Core_HostAddress = http://localhost:5000/

GET {{ProposalAPI.Core_HostAddress}}/proposals/
Accept: application/json

###

GET {{ProposalAPI.Core_HostAddress}}/proposals/1
Accept: application/json

###
